name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Test Streamlit App (Optional)
      run: |
        streamlit hello
      env:
        STREAMLIT_PORT: 8501

  deploy:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: test # Ensure deployment happens only after successful tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-recommendation-system:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/movie-recommendation-system:${{ github.ref_name }}

    - name: Deploy Streamlit App
      if: startsWith(github.ref_name, 'v')
      run: |
        echo "Deploy Streamlit app using your preferred deployment method (e.g., Cloud Run, ECS, or Heroku)."
